title: IoTFoundry
description: Umbrella architecture and governance for the IoTFoundry project family
baseurl: "/iot-foundry"
url: "https://PICMG.github.io/iot-foundry"
theme: minima

permalink: /:path/

collections:
  architecture:
    output: true
    permalink: /architecture/:path/
